updated version of reek because bundled version was too old and conflicted with rake version >= 11.0.0 (NoMethodError: undefined method `last_comment').